---

apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app: validator
  name: validator

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: validator
  name: validator
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - '*'

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: validator
  name: validator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: validator
subjects:
  - kind: ServiceAccount
    name: validator
