name: Docker Image

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: 'Publish'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 'Build and push'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            mantalabs/validator-elector:latest
            mantalabs/validator-elector:${{ github.sha }}
