name: Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 'Build and push'
        uses: 'docker/build-push-action@v2'
        with:
          push: true
          tags: mantalabs/validator-elector:${{ github.sha }}
